/* The following code was generated by JFlex 1.7.0 */

package se.su.ling.stagger;
import java.util.*;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/Users/ikwattro/dev/stagger/src/LatinTokenizer.flex</tt>
 */
public class LatinTokenizer extends Tokenizer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\15\1\101\1\101\1\14\22\0\1\13\1\52\1\55"+
    "\1\30\1\37\1\31\1\30\1\36\1\46\1\42\1\55\1\31\1\51"+
    "\1\27\1\26\1\24\3\20\1\45\6\20\1\6\1\34\1\44\1\41"+
    "\1\50\1\53\1\32\2\33\1\75\1\5\1\74\1\23\1\100\1\21"+
    "\1\11\3\33\1\76\1\73\1\40\1\22\1\33\1\77\1\10\1\3"+
    "\2\33\1\25\1\33\1\47\1\33\1\1\1\30\1\12\1\43\1\7"+
    "\1\55\2\33\1\75\1\5\1\74\1\23\1\100\1\21\1\11\3\33"+
    "\1\76\1\73\1\40\1\22\1\33\1\77\1\10\1\3\2\33\1\25"+
    "\1\35\1\47\1\33\3\55\1\30\6\0\1\16\32\0\1\13\37\55"+
    "\27\60\1\55\37\60\1\55\70\60\2\4\115\60\1\2\u01f0\0\220\61"+
    "\u0200\0\140\62\12\63\206\62\12\63\6\62\120\0\60\62\100\0\12\17"+
    "\u0136\0\146\64\12\65\20\64\146\0\12\17\166\0\12\17\166\0\12\17"+
    "\166\0\12\17\166\0\12\17\166\0\12\17\166\0\12\17\166\0\12\17"+
    "\166\0\12\17\140\0\12\17\166\0\12\17\106\0\12\17\u0116\0\12\17"+
    "\106\0\12\17\146\0\u0100\67\u05e0\0\12\17\46\0\12\17\u012c\0\12\17"+
    "\200\0\12\17\246\0\12\17\6\0\12\17\266\0\12\17\126\0\12\17"+
    "\206\0\12\17\6\0\12\17\166\0\60\64\u0200\0\u0100\61\16\13\2\0"+
    "\6\54\22\55\1\57\1\57\33\55\u0fbb\0\1\56\37\55\40\0\300\66"+
    "\60\0\140\67\u0270\0\u19c0\70\100\0\u5200\70\u0620\0\12\17\u02a6\0\12\17"+
    "\6\0\40\64\12\17\126\0\40\67\120\0\12\17\26\0\12\17\126\0"+
    "\12\17\u0196\0\12\17\u2bb6\0\120\67\100\72\60\71\u0790\72\u1b50\0\u02b0\62"+
    "\160\0\220\62\20\0\12\17\113\0\73\66\u0500\0\12\17\u0bbc\0\12\17"+
    "\200\0\12\17\74\0\12\17\220\0\12\17\u0116\0\12\17\u0156\0\12\17"+
    "\166\0\12\17\u0176\0\12\17\146\0\12\17\146\0\12\17\u01a6\0\12\17"+
    "\u0366\0\12\17\u4e06\0\12\17\346\0\12\17\u6c74\0\62\17\u1150\0\12\17"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u16b5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\3\2\2\1\3\1\2\1\4"+
    "\1\0\1\5\2\6\2\3\1\2\1\3\1\7\1\10"+
    "\1\3\1\2\1\3\6\2\1\7\1\10\2\2\1\11"+
    "\2\12\2\13\1\14\1\15\1\16\1\1\4\0\1\17"+
    "\3\0\1\17\2\0\1\20\1\0\1\21\2\3\1\0"+
    "\1\2\1\17\3\0\1\17\1\0\1\17\1\2\1\0"+
    "\1\17\6\0\2\3\3\17\5\0\1\3\1\0\1\3"+
    "\2\0\1\22\2\0\1\22\1\0\1\23\2\0\1\22"+
    "\1\0\1\23\2\22\1\24\1\23";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\306\0\u0108\0\u014a\0\u018c\0\u01ce"+
    "\0\u0210\0\102\0\u0252\0\u0294\0\u02d6\0\u0318\0\u035a\0\u039c"+
    "\0\u03de\0\u0420\0\u0462\0\u04a4\0\u04e6\0\u0528\0\u056a\0\u05ac"+
    "\0\u05ee\0\u0630\0\u0672\0\u06b4\0\u06f6\0\u0738\0\u077a\0\102"+
    "\0\u0252\0\u02d6\0\u07bc\0\u07fe\0\u0840\0\u0882\0\u08c4\0\102"+
    "\0\102\0\102\0\u0906\0\u0948\0\u01ce\0\u098a\0\u09cc\0\102"+
    "\0\u0a0e\0\u056a\0\u0630\0\u0a50\0\u0a50\0\u0a92\0\u0252\0\u0ad4"+
    "\0\u0b16\0\u0b58\0\u0b9a\0\u04e6\0\u0bdc\0\u0c1e\0\u0c60\0\u0ca2"+
    "\0\u0ce4\0\u05ee\0\u0d26\0\u0672\0\u0d68\0\u0daa\0\u0dec\0\u0e2e"+
    "\0\u0e70\0\u0eb2\0\u0ef4\0\u0f36\0\u0f78\0\u0fba\0\u0ffc\0\u0c60"+
    "\0\u01ce\0\u103e\0\u1080\0\u10c2\0\u1104\0\u1146\0\u1188\0\u11ca"+
    "\0\u120c\0\u124e\0\u1290\0\u12d2\0\u01ce\0\u1314\0\u1356\0\u1398"+
    "\0\u13da\0\u141c\0\u145e\0\u14a0\0\u14e2\0\u1524\0\u1566\0\u15a8"+
    "\0\u15ea\0\102\0\u0f78";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\4\1\6\1\7\1\10"+
    "\1\11\1\5\1\12\1\13\1\14\2\15\1\16\1\17"+
    "\1\20\1\6\1\21\1\22\1\23\1\24\1\25\1\12"+
    "\1\10\1\12\1\5\1\7\1\26\1\12\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\17\1\35\1\5\1\12"+
    "\1\36\2\37\1\40\1\12\1\41\1\42\1\4\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\2\6\5\105\0\1\54\5\0\1\54\73\0\4\4"+
    "\2\0\2\4\7\0\3\4\1\0\1\4\5\0\1\4"+
    "\1\0\1\4\2\0\1\4\6\0\1\4\10\0\1\4"+
    "\12\0\6\4\3\0\1\4\1\5\1\4\1\5\1\0"+
    "\1\55\2\5\6\0\1\55\3\5\1\0\1\5\1\56"+
    "\1\55\1\0\1\55\1\57\1\5\1\0\1\5\2\0"+
    "\1\5\4\0\1\55\1\0\1\5\10\0\1\4\12\0"+
    "\6\5\3\0\1\4\1\5\1\4\1\6\1\60\1\55"+
    "\1\11\1\5\6\0\1\55\1\5\1\6\1\5\1\0"+
    "\1\5\1\56\1\61\1\0\1\55\1\57\1\5\1\60"+
    "\1\5\1\0\1\62\1\5\1\60\1\63\2\0\1\55"+
    "\1\63\1\5\10\0\1\4\12\0\6\5\6\0\1\64"+
    "\2\0\1\64\11\0\1\64\4\0\1\65\6\0\1\66"+
    "\1\64\1\60\1\0\1\64\3\0\1\64\36\0\1\55"+
    "\1\0\1\55\1\0\3\55\6\0\4\55\1\0\3\55"+
    "\1\0\1\55\1\57\1\55\1\0\1\55\2\0\1\55"+
    "\4\0\1\55\1\0\1\55\23\0\6\55\3\0\1\4"+
    "\1\5\1\4\1\11\1\60\1\55\1\11\1\5\6\0"+
    "\1\55\1\5\1\11\1\5\1\0\1\5\1\56\1\61"+
    "\1\0\1\55\1\57\1\5\1\60\1\5\1\0\1\62"+
    "\1\5\1\0\1\62\2\0\1\55\1\62\1\5\10\0"+
    "\1\4\12\0\6\5\14\0\1\67\1\14\2\15\37\0"+
    "\1\67\1\15\37\0\1\15\77\0\1\15\1\70\2\71"+
    "\37\0\1\15\1\71\41\0\2\16\24\0\1\16\15\0"+
    "\1\16\1\0\1\16\17\0\1\55\1\0\1\55\1\0"+
    "\3\55\5\0\1\16\1\17\3\55\1\0\3\55\1\0"+
    "\1\55\1\57\1\55\1\0\1\55\2\0\1\55\4\0"+
    "\1\17\1\0\1\55\13\0\1\16\1\0\1\16\5\0"+
    "\6\55\3\0\1\4\1\21\1\4\1\5\1\0\1\55"+
    "\2\5\6\0\1\55\3\5\1\0\1\5\1\56\1\55"+
    "\1\0\1\55\1\57\1\5\1\0\1\5\2\0\1\5"+
    "\4\0\1\55\1\0\1\5\10\0\1\4\12\0\6\5"+
    "\3\0\1\4\1\72\1\4\1\5\1\0\1\55\2\5"+
    "\6\0\1\55\3\5\1\0\1\5\1\56\1\55\1\0"+
    "\1\55\1\57\1\5\1\0\1\5\2\0\1\5\4\0"+
    "\1\55\1\0\1\5\10\0\1\4\12\0\6\5\25\0"+
    "\1\22\57\0\1\4\1\5\1\4\1\5\1\0\1\55"+
    "\2\5\6\0\1\55\3\5\1\0\1\73\1\56\1\55"+
    "\1\0\1\55\1\57\1\5\1\0\1\5\2\0\1\5"+
    "\4\0\1\55\1\0\1\5\10\0\1\4\12\0\6\5"+
    "\4\0\1\55\1\0\1\55\1\0\3\55\6\0\4\55"+
    "\1\0\1\55\1\24\1\55\1\0\1\55\1\57\1\55"+
    "\1\0\1\55\2\0\1\55\4\0\1\55\1\0\1\55"+
    "\2\0\2\37\17\0\6\55\4\0\1\55\1\0\1\55"+
    "\1\0\3\55\6\0\4\55\1\0\2\55\1\74\1\0"+
    "\1\55\1\57\1\55\1\0\1\55\2\0\1\55\4\0"+
    "\1\55\1\0\1\55\1\75\22\0\6\55\3\0\1\4"+
    "\1\5\1\4\1\76\1\0\1\55\1\76\1\5\6\0"+
    "\1\55\1\5\1\76\1\5\1\0\1\5\1\56\1\77"+
    "\1\0\1\55\1\57\1\5\1\0\1\5\1\66\1\64"+
    "\1\5\1\0\1\64\2\0\1\55\1\64\1\5\10\0"+
    "\1\4\12\0\6\5\6\0\1\62\1\60\1\0\1\62"+
    "\11\0\1\62\4\0\1\100\4\0\1\60\2\0\1\62"+
    "\2\0\1\62\3\0\1\62\35\0\1\4\1\5\1\4"+
    "\1\5\1\0\1\101\2\5\6\0\1\55\3\5\1\0"+
    "\1\5\1\56\1\55\1\0\1\55\1\57\1\5\1\0"+
    "\1\5\2\0\1\5\4\0\1\55\1\0\1\5\10\0"+
    "\1\4\12\0\6\5\6\0\1\102\14\0\1\102\17\0"+
    "\1\102\3\0\1\102\40\0\1\63\1\60\1\0\1\62"+
    "\11\0\1\63\4\0\1\100\4\0\1\60\2\0\1\62"+
    "\1\0\1\60\1\63\3\0\1\63\42\0\1\103\33\0"+
    "\1\104\65\0\1\105\14\0\1\106\1\107\41\0\1\63"+
    "\1\60\1\0\1\62\11\0\1\63\4\0\1\100\4\0"+
    "\1\60\2\0\1\62\1\0\1\60\1\63\3\0\1\63"+
    "\1\110\103\0\1\36\102\0\2\37\107\0\1\43\102\0"+
    "\2\44\35\0\2\16\24\0\1\16\14\0\1\44\1\45"+
    "\1\0\1\16\100\0\2\46\33\0\2\16\24\0\1\16"+
    "\15\0\1\16\1\46\1\47\105\0\2\52\12\0\1\111"+
    "\101\0\1\55\1\0\1\55\1\0\3\55\6\0\4\55"+
    "\1\0\3\55\1\0\1\55\1\57\1\55\1\0\1\55"+
    "\2\0\1\112\4\0\1\55\1\0\1\55\23\0\1\113"+
    "\1\55\1\114\3\55\4\0\1\115\1\0\1\115\2\0"+
    "\2\115\6\0\4\115\1\0\3\115\3\0\1\115\1\0"+
    "\1\115\2\0\1\115\4\0\1\115\1\0\1\115\23\0"+
    "\6\115\4\0\1\55\1\0\1\55\1\60\3\55\6\0"+
    "\4\55\1\0\3\55\1\0\1\55\1\57\1\55\1\60"+
    "\1\55\2\0\1\55\4\0\1\55\1\0\1\55\23\0"+
    "\6\55\6\0\1\64\2\0\1\64\11\0\1\64\14\0"+
    "\1\64\2\0\1\64\3\0\1\64\40\0\1\64\2\0"+
    "\1\64\11\0\1\64\4\0\1\65\7\0\1\64\2\0"+
    "\1\64\3\0\1\64\50\0\1\71\77\0\1\71\1\70"+
    "\2\71\37\0\2\71\24\0\1\4\1\5\1\4\1\5"+
    "\1\0\1\55\2\5\6\0\1\55\1\5\1\116\1\5"+
    "\1\0\1\5\1\56\1\55\1\0\1\55\1\57\1\5"+
    "\1\0\1\5\2\0\1\5\4\0\1\55\1\0\1\5"+
    "\10\0\1\4\12\0\6\5\3\0\1\4\1\5\1\4"+
    "\1\5\1\0\1\55\2\5\6\0\1\55\3\5\1\0"+
    "\1\117\1\56\1\55\1\0\1\55\1\57\1\5\1\0"+
    "\1\5\2\0\1\5\4\0\1\55\1\0\1\5\10\0"+
    "\1\4\12\0\6\5\51\0\1\75\33\0\1\4\1\5"+
    "\1\4\1\76\1\0\1\55\1\76\1\5\6\0\1\55"+
    "\1\5\1\76\1\5\1\0\1\5\1\56\1\55\1\0"+
    "\1\55\1\57\1\5\1\0\1\5\1\0\1\64\1\5"+
    "\1\0\1\64\2\0\1\55\1\64\1\5\10\0\1\4"+
    "\12\0\6\5\4\0\1\55\1\0\1\120\1\0\1\55"+
    "\1\120\1\55\6\0\2\55\1\120\1\55\1\0\3\55"+
    "\1\0\1\55\1\57\1\55\1\0\1\55\1\0\1\64"+
    "\1\55\1\0\1\64\2\0\1\55\1\64\1\55\23\0"+
    "\6\55\7\0\1\60\25\0\1\60\50\0\1\55\1\0"+
    "\1\55\1\0\3\55\6\0\4\55\1\0\3\55\1\0"+
    "\1\55\1\57\1\55\1\0\1\55\2\0\1\121\4\0"+
    "\1\55\1\0\1\55\23\0\6\55\10\0\1\103\33\0"+
    "\1\122\65\0\1\105\101\0\1\105\14\0\1\106\102\0"+
    "\1\107\76\0\1\60\43\0\1\123\4\0\1\123\73\0"+
    "\1\55\1\0\1\55\1\0\3\55\6\0\4\55\1\0"+
    "\3\55\1\0\1\55\1\57\1\55\1\0\1\55\2\0"+
    "\1\55\4\0\1\55\1\0\1\55\23\0\4\55\1\124"+
    "\1\55\4\0\1\55\1\0\1\55\1\0\3\55\6\0"+
    "\4\55\1\0\3\55\1\0\1\55\1\57\1\55\1\0"+
    "\1\55\2\0\1\55\4\0\1\55\1\0\1\55\23\0"+
    "\1\55\1\125\4\55\4\0\1\55\1\0\1\55\1\0"+
    "\3\55\6\0\4\55\1\0\3\55\1\0\1\55\1\57"+
    "\1\55\1\0\1\55\2\0\1\126\4\0\1\55\1\0"+
    "\1\55\23\0\6\55\4\0\1\115\1\0\1\115\2\0"+
    "\2\115\6\0\4\115\1\0\1\115\1\127\1\115\3\0"+
    "\1\115\1\0\1\115\2\0\1\115\4\0\1\115\1\0"+
    "\1\115\23\0\6\115\3\0\1\130\1\5\1\4\1\5"+
    "\1\131\1\55\1\132\1\5\6\0\1\55\3\5\1\0"+
    "\1\5\1\56\1\55\1\0\1\55\1\57\1\5\1\0"+
    "\1\5\2\0\1\5\4\0\1\55\1\0\1\5\10\0"+
    "\1\4\12\0\6\5\3\0\1\4\1\5\1\4\1\5"+
    "\1\0\1\55\2\5\6\0\1\55\3\5\1\0\1\5"+
    "\1\133\1\55\1\0\1\55\1\57\1\5\1\0\1\5"+
    "\2\0\1\5\4\0\1\55\1\0\1\5\10\0\1\4"+
    "\12\0\6\5\44\0\1\122\43\0\1\134\77\0\1\55"+
    "\1\0\1\55\1\0\3\55\6\0\4\55\1\0\3\55"+
    "\1\0\1\55\1\57\1\55\1\0\1\55\2\0\1\55"+
    "\4\0\1\55\1\0\1\55\23\0\5\55\1\135\4\0"+
    "\1\135\1\0\1\55\1\0\3\55\6\0\4\55\1\0"+
    "\3\55\1\0\1\55\1\57\1\55\1\0\1\55\2\0"+
    "\1\55\4\0\1\55\1\0\1\55\23\0\6\55\4\0"+
    "\1\55\1\0\1\55\1\0\3\55\6\0\4\55\1\0"+
    "\3\55\1\0\1\55\1\57\1\55\1\0\1\55\2\0"+
    "\1\55\4\0\1\55\1\0\1\55\23\0\3\55\1\135"+
    "\2\55\4\0\1\136\1\0\1\136\2\0\2\136\6\0"+
    "\1\115\3\136\1\0\1\136\1\127\1\115\3\0\1\136"+
    "\1\0\1\136\2\0\1\136\4\0\1\115\1\0\1\136"+
    "\23\0\6\136\3\0\4\4\1\131\1\0\2\4\7\0"+
    "\3\4\1\0\1\4\5\0\1\4\1\0\1\4\2\0"+
    "\1\4\6\0\1\4\10\0\1\4\12\0\6\4\25\0"+
    "\1\137\57\0\1\4\1\5\1\4\1\5\1\131\1\55"+
    "\2\5\6\0\1\55\3\5\1\0\1\5\1\56\1\55"+
    "\1\0\1\55\1\57\1\5\1\0\1\5\2\0\1\5"+
    "\4\0\1\55\1\0\1\5\10\0\1\4\12\0\6\5"+
    "\4\0\1\140\1\0\1\140\1\0\1\55\2\140\6\0"+
    "\4\140\1\0\1\140\1\55\1\140\1\0\1\55\1\57"+
    "\1\140\1\0\1\140\2\0\1\140\4\0\1\140\1\0"+
    "\1\140\23\0\6\140\7\0\1\141\76\0\1\142\1\0"+
    "\1\142\2\0\2\142\6\0\1\115\3\142\1\0\1\142"+
    "\1\127\1\115\3\0\1\142\1\0\1\142\2\0\1\142"+
    "\4\0\1\115\1\0\1\142\23\0\6\142\25\0\1\143"+
    "\60\0\1\140\1\0\1\140\1\144\1\55\2\140\6\0"+
    "\4\140\1\145\1\140\1\133\1\140\1\0\1\55\1\57"+
    "\1\140\1\0\1\140\2\0\1\140\4\0\1\140\1\0"+
    "\1\140\23\0\6\140\4\0\1\146\1\0\1\146\1\0"+
    "\3\146\6\0\4\146\1\0\1\146\1\0\1\146\3\0"+
    "\1\146\1\0\1\146\2\0\1\146\4\0\1\146\1\0"+
    "\1\146\23\0\6\146\4\0\1\147\1\0\1\147\2\0"+
    "\2\147\6\0\1\115\3\147\1\0\1\147\1\127\1\115"+
    "\3\0\1\147\1\0\1\147\2\0\1\147\4\0\1\115"+
    "\1\0\1\147\23\0\6\147\4\0\1\150\1\0\1\150"+
    "\2\0\2\150\6\0\4\150\1\0\1\150\1\0\1\150"+
    "\3\0\1\150\1\0\1\150\2\0\1\150\4\0\1\150"+
    "\1\0\1\150\23\0\6\150\21\0\1\151\24\0\1\151"+
    "\37\0\1\145\1\0\5\145\6\0\16\145\1\0\4\145"+
    "\2\0\3\145\1\0\1\145\1\0\1\145\17\0\6\145"+
    "\4\0\1\146\1\0\1\146\1\0\3\146\1\152\5\0"+
    "\4\146\1\0\1\146\1\0\1\146\3\0\1\146\1\0"+
    "\1\146\2\0\1\146\4\0\1\146\1\0\1\146\23\0"+
    "\6\146\4\0\1\153\1\0\1\153\2\0\2\153\6\0"+
    "\1\115\3\153\1\0\1\153\1\127\1\115\3\0\1\153"+
    "\1\0\1\153\2\0\1\153\4\0\1\115\1\0\1\153"+
    "\23\0\6\153\4\0\1\150\1\0\1\150\1\144\1\0"+
    "\2\150\6\0\4\150\1\145\1\150\1\143\1\150\3\0"+
    "\1\150\1\0\1\150\2\0\1\150\4\0\1\150\1\0"+
    "\1\150\23\0\6\150\21\0\1\151\3\0\1\145\20\0"+
    "\1\151\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5676];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\1\1\1\0\23\1\1\11"+
    "\7\1\3\11\1\1\4\0\1\11\3\0\1\1\2\0"+
    "\1\1\1\0\3\1\1\0\2\1\3\0\1\1\1\0"+
    "\2\1\1\0\1\1\6\0\5\1\5\0\1\1\1\0"+
    "\1\1\2\0\1\1\2\0\1\1\1\0\1\1\2\0"+
    "\1\1\1\0\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public ArrayList<Token> readSentence() throws IOException {
    ArrayList<Token> sentence = new ArrayList<Token>();
    Token token, lastNonSpace = null, lastSpace = null;

    while((token = yylex()) != null) {
        if(token.isSpace()) {
            if(token.type == Token.TOK_NEWLINES) {
                if(!sentence.isEmpty()) return sentence;
            }
            lastSpace = token;
        } else {
            if(!sentence.isEmpty()) {
                if(lastSpace != null && lastSpace.type != Token.TOK_SPACE &&
                   token.isCapitalized())
                {
                    yypushback(yylength());
                    return sentence;
                } else if(lastNonSpace != null &&
                        lastNonSpace.value.endsWith(".") &&
                        token.isCapitalized())
                {
                    yypushback(yylength());
                    return sentence;
                } else if(token.type == Token.TOK_SENT_FINAL) {
                    sentence.add(token);
                    return sentence;
                }
            }
            sentence.add(token);
            lastNonSpace = token;
        }
    }
    if(sentence.isEmpty()) return null;
    return sentence;
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LatinTokenizer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 532) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return(new Token(Token.TOK_UNKNOWN,yytext(),yychar));
            } 
            // fall through
          case 21: break;
          case 2: 
            { return(new Token(Token.TOK_SYMBOL,yytext(),yychar));
            } 
            // fall through
          case 22: break;
          case 3: 
            { return(new Token(Token.TOK_LATIN,yytext(),yychar));
            } 
            // fall through
          case 23: break;
          case 4: 
            { return(new Token(Token.TOK_SPACE,yytext(),yychar));
            } 
            // fall through
          case 24: break;
          case 5: 
            { return(new Token(Token.TOK_NEWLINE,yytext(),yychar));
            } 
            // fall through
          case 25: break;
          case 6: 
            { return(new Token(Token.TOK_NUMBER,yytext(),yychar));
            } 
            // fall through
          case 26: break;
          case 7: 
            { return(new Token(Token.TOK_SENT_FINAL,yytext(),yychar));
            } 
            // fall through
          case 27: break;
          case 8: 
            { return(new Token(Token.TOK_DASH,yytext(),yychar));
            } 
            // fall through
          case 28: break;
          case 9: 
            { return(new Token(Token.TOK_GREEK,yytext(),yychar));
            } 
            // fall through
          case 29: break;
          case 10: 
            { return(new Token(Token.TOK_ARABIC,yytext(),yychar));
            } 
            // fall through
          case 30: break;
          case 11: 
            { return(new Token(Token.TOK_NAGARI,yytext(),yychar));
            } 
            // fall through
          case 31: break;
          case 12: 
            { return(new Token(Token.TOK_KANA,yytext(),yychar));
            } 
            // fall through
          case 32: break;
          case 13: 
            { return(new Token(Token.TOK_HANGUL,yytext(),yychar));
            } 
            // fall through
          case 33: break;
          case 14: 
            { return(new Token(Token.TOK_HANZI,yytext(),yychar));
            } 
            // fall through
          case 34: break;
          case 15: 
            { return(new Token(Token.TOK_SMILEY,yytext(),yychar));
            } 
            // fall through
          case 35: break;
          case 16: 
            { return(new Token(Token.TOK_SPACES,yytext(),yychar));
            } 
            // fall through
          case 36: break;
          case 17: 
            { return(new Token(Token.TOK_NEWLINES,yytext(),yychar));
            } 
            // fall through
          case 37: break;
          case 18: 
            { return(new Token(Token.TOK_URL,yytext(),yychar));
            } 
            // fall through
          case 38: break;
          case 19: 
            { return(new Token(Token.TOK_EMAIL,yytext(),yychar));
            } 
            // fall through
          case 39: break;
          case 20: 
            { sentID = yytext().substring(6, yylength()-1);
            } 
            // fall through
          case 40: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
